import "./globals.css";
import Navbar from "@/components/Navbar";
import { Luckiest_Guy } from 'next/font/google';

const luckiestGuy = Luckiest_Guy({
  weight: '400',
  subsets: ['latin'],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${luckiestGuy.className} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
